import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './auth.css'
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <div
      className={`
        auth-bg              
        font-sf-pro text-white overflow-y-hidden h-screen ${geistSans.variable} ${geistMono.variable} antialiased
      `}
    >
      {children}
    </div>
  );
}
